name: Build ccminer
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build
        run: sudo apt update && sudo apt install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential -y

      - name: Build
        run: chmod +x ./${{ github.workspace }}/ccminer/build.sh && ./${{ github.workspace }}/ccminer/build.sh
     
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
         name: ccminer        # The name given to your uploaded file(s)
         path: ${{ github.workspace }}/ccminer/ccminer
